version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/distributed_analysis.wdl
    readMePath: /README.md
    name: distributed_analysis
    authors:
      -  name: Leah Maciel
         email: lmaciel@broadinstitute.org
    topic: Distributed workflow for contractility analysis of ring tissues
    testParameterFiles:
      - /wdl/distributed_analysis.json

  - subclass: WDL
    primaryDescriptorPath: /wdl/analyze_folder.wdl
    readMePath: /README.md
    name: analyze_folder
    authors:
       -  name: Leah Maciel
          email: lmaciel@broadinstitute.org
    topic: Sequential workflow for contractility analysis of ring tissues
    testParameterFiles:
      - /wdl/analyze_ring_tissue_videos.json
